- name: Machine setup
  hosts: localhost
  vars:
    default_shell: zsh
  tasks:
    - name: Include OS-specific setup tasks
      ansible.builtin.include_tasks: tasks/setup-{{ ansible_os_family }}.yaml

    - name: Change default shell to zsh if it's currently not
      ansible.builtin.script: scripts/change_default_shell_to_zsh.sh {{ lookup('env', 'USER')}}
      become: true

    - name: Check if rustup installed
      shell: command -v rustup >/dev/null 2>&1
      register: is_rustup_exist
      args:
        executable: /usr/bin/{{default_shell}}
      ignore_errors: true

    - name: Install rustup
      ansible.builtin.shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      when: is_rustup_exist.rc == 1
      args:
        executable: /bin/sh

    - name: Install antidote
      ansible.builtin.git:
        repo: https://github.com/mattmc3/antidote.git
        dest: ~/.antidote/
        depth: 1

    - name: Install common packages from cargo
      community.general.cargo:
        name:
          - vivid
          - fnm
          - tealdeer
          - eza

    - name: Install pure prompt
      ansible.builtin.git:
        repo: https://github.com/sindresorhus/pure.git
        dest: ~/.zsh/pure

    - name: Run install gopass task
      ansible.builtin.include_tasks: tasks/i-gopasspw.yaml

    - name: Check if lazygit installed
      shell: command -v lazygit >/dev/null 2>&1
      register: is_lazygit_exist
      args:
        executable: /usr/bin/{{default_shell}}
      ignore_errors: true

    - name: Install lazygit
      ansible.builtin.command:
        cmd: go install github.com/jesseduffield/lazygit@latest
      become: true
